application:
  port: 8000
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  sender_email: "test@mail.com"
  password: "password123"
  timeout_milliseconds: 10000
  smtp_server: "smtp.mail.com"
